- arguments:
    - -XAllowAmbiguousTypes
    - -XApplicativeDo
    - -XDerivingStrategies
    - -XInstanceSigs
    - -XLambdaCase
    - -XMonoLocalBinds
    - -XNamedFieldPuns
    - -XOverloadedRecordDot
    - -XOverloadedRecordUpdate
    - -XOverloadedStrings
    - -XQuantifiedConstraints
    - -XRebindableSyntax
    - -XRecordWildCards
    - -XScopedTypeVariables
- group:
    name: generalise
    enabled: true
- group:
    name: generalise-for-conciseness
    enabled: true
- group:
    name: partial
    enabled: true
- group:
    name: future
    enabled: true
- group:
    name: dollar
    enabled: true
- group:
    name: monomorphic
    enabled: true
- group:
    name: teaching
    enabled: true
# Not yet enabled
- group:
    name: extra
    enabled: false
# Disabled warnings
- ignore:
    name: "Use if"